#include <iostream>
using namespace std;
int main(){
int age = 5;
float num = 1.9;
double num1 = 2.88;
string name = "Ritik";
 int a = 10;
 int b = 5;
 int p = 100;
 int r = 2;
 int t = 10;
 float si = (p*r*t)/100;
 if (si > (50/100) * p){
    cout << "you need to pay tax" << endl;
 } else {
    cout << "you don't need to pay tax" << endl;;
 }
int n = 5;
 for (int i = 0; i < n; i++){
   for (int j = 0; j < n; j++)
     cout << "*" << " " ;
     cout << endl;
 }


// cout << (a > b) << endl;
// cout << age;
};